import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat, Libre_Baskerville, Urbanist } from 'next/font/google'
import SmoothFollower from "@/components/ui/cursor";
import Navbar from "@/components/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({ 
  variable: "--font-montserrat",
  subsets: ['latin'] 
})
const libreBaskerville = Libre_Baskerville({ 
  variable: "--font-libre-baskerville",
  weight: ['400', '700'],
  subsets: ['latin'] 
})
const urbanist = Urbanist({
  variable: "--font-urbanist", 
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="fr" className="scroll-smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="description" content="A unique shopping experience in our digital showcase." />
        <meta name="keywords" content="shopping, digital showcase, unique experience, premium quality" />
        <meta name="author" content="La Petite Vitrine" />
        <meta property="og:title" content="La Petite Vitrine" />
        <meta property="og:description" content="Explore exceptional products with unmatched quality." />
        <meta property="og:image" content="/og-image.jpg" />
        <meta property="og:url" content="https://yourwebsite.com" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="La Petite Vitrine" />
        <meta name="twitter:description" content="Explore exceptional products with unmatched quality." />
        <meta name="twitter:image" content="/og-image.jpg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${libreBaskerville.variable} ${urbanist.variable} antialiased overflow-x-hidden`}
      >
        <SmoothFollower />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
